name: hierarch
channels:
  - rkulk111
  - defaults
  - conda-forge
dependencies:
  - ca-certificates=2021.5.25
  - certifi=2021.5.30
  - openssl=1.1.1k
  - pip=21.1.1
  - python=3.8.10
  - setuptools=52.0.0
  - sqlite=3.35.4
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.36.2
  - wincertstore=0.2
  - llvmlite==0.36.0
  - numba==0.53.1
  - numpy==1.21.0rc1
  - pandas==1.2.4
  - python-dateutil==2.8.1
  - pytz==2021.1
  - scipy==1.6.3
  - six==1.16.0

