{% set name = "hierarch" %}
{% set version = "1.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hierarch-{{ version }}.tar.gz
  sha256: 76195e79358a3be3dfd05367f4a7f71b5a0bd2930651508e84a234d34b3c4194

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - numba >=0.53.1
    - numpy >=1.20.2
    - pandas >=1.2.4
    - python >=3.7
    - scipy >=1.6.2

test:
  imports:
    - hierarch
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/rishi-kulkarni/hierarch
  summary: Hierarchical hypothesis testing library
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - rishi-kulkarni
